# Generated by Django 4.2.1 on 2023-08-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_options_expense_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='transaction_type',
            field=models.CharField(choices=[('Income', 'Income'), ('Income', 'Expense')], default='Expense', max_length=15),
        ),
    ]
