# Generated by Django 4.2.1 on 2023-08-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_expense_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('Income', 'Income'), ('Expense', 'Expense')], default='Expense', max_length=16, null=True),
        ),
    ]
